name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build
        run: sleep 60

  test:
    runs-on: macos-latest
    steps:
      - name: Test
        run: sleep 60
